### ISSUE TITLE
sh: 1: Syntax error: ")" unexpected

### ISSUE THREAD

**Issue by Muhammad95959** [AnirudhG07/archivemount.yazi#3]
![image](https://github.com/user-attachments/assets/9e7283f2-1013-473d-b002-f78f13c8bbe5)
When I hover over a file named `08 - Was Turtles Forever Actually Good？ (It's Complicated)` I get this error `sh: 1: Syntax error: ")" unexpected` This error only occurs with this plugin

**Comment by AnirudhG07** [comment]
How is this related to archivemount.yazi? I didn't get you.
Can you send some reproducing steps for it which involved this plugin? I saw ur issue in main Yazi repo as well. From the steps u told there, I didn't face any issues making it.

**Comment by Muhammad95959** [comment]
![image](https://github.com/user-attachments/assets/964111fe-0271-4bd5-9b8f-ee0ffa4bf0c9)

I disabled every plugin i have except for this one and I got the same error

**Comment by AnirudhG07** [comment]
Can you just confirm, if you remove the UI extension, from your main init.lua, the issue still persists or not? Cause the backend functionality shoudnt have anything to do with this issue.

**Comment by Muhammad95959** [comment]
I'm not sure what you mean by the UI extension
but if you're asking whether the error persists without the plugin then no it goes away

**Comment by AnirudhG07** [comment]
No I mean remove the `require("archivemount"):setup()` from your init.lua

**Comment by Muhammad95959** [comment]
that fixed the issue

**Comment by AnirudhG07** [comment]
I see. Thanks for telling about it. I'll see how I can fix it on my end. The UI extension should not cause all this.
